/* eslint-disable @typescript-eslint/no-explicit-any */
import { type Format } from "./Format";

export interface Metadata {
  id: string;
  title: string;
  formats: Format[];
  thumbnails: any[];
  thumbnail: string;
  description: string;
  channel_id: string;
  channel_url: string;
  duration: number;
  view_count: number;
  average_rating: number | null;
  age_limit: number;
  webpage_url: string;
  categories: string[];
  tags: string[];
  playable_in_embed: boolean;
  live_status: string;
  media_type: "audio" | "video";
  release_timestamp: number | null;
  _format_sort_fields: string[];
  automatic_captions: any;
  subtitles: any;
  album: string;
  artists: string[];
  track: string;
  release_date: number | null;
  release_year: number;
  comment_count: number;
  chapters: number | null;
  heatmap: null;
  like_count: number;
  channel: string;
  channel_follower_count: number;
  creators: string[];
  channel_is_verified: boolean;
  uploader: string;
  uploader_id: string | null;
  uploader_url: string | null;
  upload_date: string;
  timestamp: number;
  alt_title: string;
  availability: "public" | "private";
  original_url: string;
  webpage_url_basename: string;
  webpage_url_domain: "youtube.com";
  extractor: "youtube";
  extractor_key: "Youtube";
  playlist: null;
  playlist_index: null;
  display_id: string;
  fulltitle: string;
  duration_string: `${number}:${number}`;
  is_live: boolean;
  was_live: boolean;
  artist: string;
  creator: string;
  requested_subtitles: null;
  _has_drm: null;
  epoch: number;
  requested_formats: object[];
  format: string;
  format_id: string;
  ext: string;
  protocol: string;
  language: string | null;
  format_note: string;
  filesize_approx: number;
  tbr: number;
  width: number;
  height: number;
  resolution: `${number}x${number}`;
  fps: number;
  dynamic_range: string;
  vcodec: string;
  vbr: number;
  stretched_ratio: number | null;
  aspect_ratio: number;
  acodec: string;
  abr: number;
  asr: number;
  audio_channels: number;
  _filename: string;
  filename: string;
  _type: "video" | "audio";
  _version: {
    version: `${number}.${number}.${number}`;
    current_git_head: null;
    release_git_head: string;
    repository: "yt-dlp/yt-dlp";
  };
}
